// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF54f0XejEKxHHuGxc4PuXHn0F7x-wpZ8',
    appId: '1:784625842499:android:c5f2aa6b5f77f1b96017f6',
    messagingSenderId: '784625842499',
    projectId: 'tobuy-app-fa605',
    storageBucket: 'tobuy-app-fa605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGS-1FxYH7Zvri_uuwl1eUD294QwuWNI',
    appId: '1:784625842499:ios:43b1ffdeb121ac656017f6',
    messagingSenderId: '784625842499',
    projectId: 'tobuy-app-fa605',
    storageBucket: 'tobuy-app-fa605.firebasestorage.app',
    iosBundleId: 'com.example.tobuy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRbY8WLTcFcAvSC9EebOgAtht4gWZm6dU',
    appId: '1:784625842499:web:b237a033712774db6017f6',
    messagingSenderId: '784625842499',
    projectId: 'tobuy-app-fa605',
    authDomain: 'tobuy-app-fa605.firebaseapp.com',
    storageBucket: 'tobuy-app-fa605.firebasestorage.app',
    measurementId: 'G-R9MWZ7TET0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYGS-1FxYH7Zvri_uuwl1eUD294QwuWNI',
    appId: '1:784625842499:ios:43b1ffdeb121ac656017f6',
    messagingSenderId: '784625842499',
    projectId: 'tobuy-app-fa605',
    storageBucket: 'tobuy-app-fa605.firebasestorage.app',
    iosBundleId: 'com.example.tobuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRbY8WLTcFcAvSC9EebOgAtht4gWZm6dU',
    appId: '1:784625842499:web:b35842c75453daf76017f6',
    messagingSenderId: '784625842499',
    projectId: 'tobuy-app-fa605',
    authDomain: 'tobuy-app-fa605.firebaseapp.com',
    storageBucket: 'tobuy-app-fa605.firebasestorage.app',
    measurementId: 'G-ESJ866H766',
  );

}